version: '3'

services:
  dtl.mra.customers.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dtl.mra.meterreads.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dtl.mra.meters.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
